### ISSUE TITLE
auto generate version not working

### ISSUE THREAD

**Issue by tinkerbell1268** [superunitybuild/buildtool#138] opened 2024-05-17 18:51 UTC
After some time, auto-generate version has stopped working
unity version : 2022.3.8.f1
superunitybuild version : 7.0.0

**Comment by tinkerbell1268** [comment] 2024-05-17 18:53
After some time, auto-generate version has stopped working
unity version : 2022.3.8.f1
superunitybuild version : 7.0.0

**Comment by PupaakDev** [comment] 2024-06-25 12:47
Same here. Build counter will not go past 6.

**Comment by robinnorth** [comment] 2024-08-19 10:36
Think this is a duplicate of #35, let me know if that doesn't seem to be the case and provide some steps to reproduce and I'll re-open the issue.

**Closed by robinnorth** 2024-08-19 10:36 UTC
